const users = [
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
  {
    username: "KhoTheProgrammer",
    firstname: "Kondwani",
    lastname: "Padyera",
    email: "kondwanipadyera@gmail.com",
    password: "imaprogrammer",
  },
];
module.exports = { users };
